### ISSUE TITLE
Path Issue?

### ISSUE THREAD

**Issue by sedrickkeh** [wbhu/Mono3D#1]
Whenever I try to run the demo 
`$ python main/demo.py --left ./imgs/demo_L.png`

I get the error
`No module named base.baseTrainer`

It seems like the file cannot properly import the file inside `base`.

Also, I want to ask about the environment. In the README, it mentioned `env.yaml`, but I cannot seem to find the file.

**Comment by wbhu** [comment]
Thanks for your feedback, please try the updated repo.
