### ISSUE TITLE
Training for Video 

### ISSUE THREAD

**Issue by mcsuy1998** [wbhu/Mono3D#3]
You mention that you pass P_t-1 to the reconstructor at time t similar to an RNN. Do you use the same architecture as an RNN, in that you have a learnable linear layer that multiplies P_t-1 and then sum the result with P_t and this is what is passed onto the reconstructor?

**Comment by wbhu** [comment]
We first concatenate P_t-1 and P_t along the channel axis, and then reduce the channel dimension with a 1x1 convolution.
